a = input('Digite algo: ')
print(f'O tipo primitivo dessa variavel é: {type(a)}')
print(f'Só tem espaços? {a.isspace()}')
print(f'é um numero? {a.isnumeric()}')
print(f'é alfabetico? {a.isalpha()}')
print(f'é alphanumérico? {a.isalnum()}')
print(f'está em maiúsculas? {a.isupper()}')
print(f'está em minúsculas? {a.islower()}')
print(f'está capitalizada? {a.istitle()}') 